version: '3'
services:
  api:
    container_name: starjobs_api
    image: node:16
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./api/:/home/node/app
    ports:
      - '3001:3001'
    expose:
      - '3001'
    command: sh -c 'npm install && npm run start'
    networks:
      web:
      db:

  app:
    container_name: starjobs_app
    image: react
    build:
      context: infrastructure
      dockerfile: Dockerfile
    user: 'node'
    working_dir: /app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    volumes:
      - ./frontend/:/app
    ports:
      - '3000:3000'
    expose:
      - '3000'
    command: sh -c 'npm install && npm run start'
    depends_on:
      - api
    networks:
      web:

networks:
  web:
  db: