name: Production Deploy 
on:
  push:
    branches:
      - main
    paths:
    - 'api/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Add api remote origin
        run: |
          git remote add heroku-api https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/sj-production-environment.git
      - name: Deploy api to Heroku
        run: |
          git subtree push --prefix api heroku-api master